import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { createContext, useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const SearchContext = createContext<{
  searchTerm: string;
  setSearchTerm: (v: string) => void;
}>({ searchTerm: "", setSearchTerm: () => {} });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [searchTerm, setSearchTerm] = useState("");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 min-h-screen flex flex-col`}
      >
        <SearchContext.Provider value={{ searchTerm, setSearchTerm }}>
          <Header searchTerm={searchTerm} onSearchTermChange={setSearchTerm} />
          <main className="flex-1 w-full max-w-7xl mx-auto">{children}</main>
          <Footer />
        </SearchContext.Provider>
      </body>
    </html>
  );
}
